# Generated by Django 3.1.1 on 2020-09-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('priority', models.IntegerField(default=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('room_number', models.PositiveSmallIntegerField(unique=True)),
                ('bed_count', models.PositiveSmallIntegerField(default=1)),
                ('size', models.PositiveSmallIntegerField(default=20)),
                ('has_good_view', models.BooleanField(default=False)),
                ('price_per_min', models.FloatField(default=0.5)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('priority', models.IntegerField(default=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('price', models.FloatField(editable=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_room', to='booked.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
