# Generated by Django 3.1.1 on 2020-09-09 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('priority', models.IntegerField(default=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('rate', models.PositiveSmallIntegerField(choices=[(0, '-'), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3)),
                ('booked_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='book.bookedroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
